name: Build DesktopWidget

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore DesktopWidget.sln

    - name: Build project
      run: dotnet publish DesktopWidget.sln -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: DesktopWidget
        path: DesktopWidget/bin/Release/net7.0-windows/win-x64/publish/
